scrape_configs:
  - job_name: 'synthetic-arbitrage-api'
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['localhost:7071']
        labels:
          app_name: 'SyntheticArbitrage.API'
    tls_config:
      insecure_skip_verify: true #отключает проверку TLS-сертификата (пригодится, если self-signed или dev-сертификат)