version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: arbitrage_db
    restart: always
    environment:
      POSTGRES_DB: arbitrage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge